name: Despliegue a Databricks (Proyecto 2)

on:
  push:
    branches:
      - main # Se dispara cuando haces push a la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Bajar el código del repo de GitHub
      - name: Checkout del código
        uses: actions/checkout@v3

      # 2. Instalar Databricks CLI
      - name: Instalar Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      # 3. Sincronizar archivos corregido demo"
      - name: Sincronizar carpeta Proyecto2
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          # Cambiamos -o por --overwrite para que la nueva CLI lo reconozca
          databricks workspace import-dir . /Workspace/Users/apps.compartidos@gmail.com/Proyecto2/ --overwrite

      # 4. Sincronizar archivos a la nueva carpeta (Proyecto2)
      - name: Sincronizar carpeta Proyecto2
        run: |
          # Importante: Esto sube todo tu repo local a la ruta especificada
          databricks workspace import-dir . /Workspace/Users/apps.compartidos@gmail.com/Proyecto2/ -o